[package]
name = "vanta"
version = "0.1.0"
edition = "2021"
description = "Aesthetic Rust TUI system dashboard — monitoring meets flex widgets"
authors = ["zius"]
license = "MIT"

[dependencies]
ratatui = "0.29"
crossterm = "0.28"
sysinfo = "0.33"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
chrono = "0.4"
dbus = "0.9"
image = "0.25.10"

[dev-dependencies]
tracing = "0.1.44"
